[package]
name = "xrd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quick-xml = { version = "0.22.0", features = [ "serialize" ] }
serde = "1.0.136"
aho-corasick = "0.7.18"
serde_derive = "1.0.136"
byteorder = "1.4.3"
toml = "0.5.8"
